---
kind: pipeline
type: docker
name: default
steps:
  name: test
  image: python
  commands: 
    - lscpu
    - lscpu
  - name: test
    image: python
    commands: 
      - lscpu
      - pytest -vv
