---
kind: pipeline
type: docker
name: build2

steps:
- name: test2
  image: node
  commands:
  - lscpu

---
kind: pipeline
name: after

steps:
- name: notify
  image: plugins/slack
  settings:
    room: general
   

depends_on:
- build1
- build2
